config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

  get 'site/term', to: 'sites#term'
  resource :post_picture, only: %i[show create destroy]

  resource :account, only: %i[show destroy]
  get 'account/delete_confirm', to: 'accounts#delete_confirm'
  get 'account/delete_completed', to: 'accounts#delete_completed'

  resources :morning_activity_results, only: %i[index show create destroy]
  resource :today_morning_activity_result, only: %i[new show update]

  #twitter認証用
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  post 'oauth/logout', to: 'oauths#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/morning_activity_result.rb
class MorningActivityResult < ApplicationRecord
  belongs_to :user

  enum state: %i[not_implemented success failed]
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  has_many :morning_activity_results, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_one_attached :avatar
  has_one_attached :post_picture

  def download_and_attach_avatar(filename)
    filename = filename&.gsub(/_normal/, '')
    return unless filename

    file = open(filename)
    avatar.attach(io: file,
                  filename: "avatar.#{file.content_type_parse.first.split("/").last}",
                  content_type: file.content_type_parse.first)
  end

  def post_picture_path
    Settings.host_url + Rails.application.routes.url_helpers.rails_blob_path(post_picture)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # アカウントを削除した場合に削除完了ページに飛べないため追加
  skip_before_action :require_login, raise: false, only: %i[delete_completed]

  def show; end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    session[:user_id] = nil
    redirect_to account_delete_completed_path
  end

  def delete_confirm; end

  def delete_completed; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :danger

  private

  def not_authenticated
    redirect_to root_path, info: 'ログインしてください。'
  end
end

app/controllers/morning_activity_results_controller.rb
class MorningActivityResultsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    range = params[:month].to_date.all_month
    @month_results = current_user.morning_activity_results.where(execution_at: range)
    respond_to do |format|
      format.html
      format.json { render json: @month_results }
    end
  end

  def create
    @morning_activity_result = current_user.morning_activity_results.build(execution_at: params[:click_day].to_date, state: :not_implemented)
    @morning_activity_result.save

    respond_to do |format|
      format.html
      format.json { render json: current_user }
    end
  end

  def destroy
    @morning_activity_result = current_user.morning_activity_results.find_by(execution_at: params[:id].to_date.all_day, state: :not_implemented)
    if @morning_activity_result
      @morning_activity_result.destroy
    end

    respond_to do |format|
      format.html
      format.json { render json: current_user }
    end
  end

  # クリックした日付が登録されているか判定
  def show
    @morning_activity_result = current_user.morning_activity_results.find_by(execution_at: params[:id].to_date.all_day)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { render json: @morning_activity_result }
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]

    if @user = login_from(provider)
      redirect_to morning_activity_results_path(month: Date.current), success: "#{provider.titleize}でログインしました。"
    else
      begin
        #twitter情報取得
        @user = build_from(provider)

        @user.authentications.build(uid: @user_hash[:uid], provider: provider, access_token: @access_token.token, access_token_secret: @access_token.secret)
        @user.download_and_attach_avatar(@user_hash[:user_info]['profile_image_url_https'])
        @user.save

        reset_session
        auto_login(@user)
        redirect_to site_term_path
      rescue
        redirect_to root_path, danger: "#{provider.titleize}でログイン出来ませんでした。"
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, success: 'ログアウトしました。'
  end
end

app/controllers/post_pictures_controller.rb
class PostPicturesController < ApplicationController

  def show; end

  def create
    if params[:post_picture]
      current_user.post_picture.attach(params[:post_picture])
      redirect_to morning_activity_results_path(month: Date.current), success: '画像を登録しました。'
    else
      flash[:danger] = '画像が選択されていません。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if current_user.post_picture.attached?
      current_user.post_picture.purge
    end
    redirect_to morning_activity_results_path(month: Date.current), success: 'デフォルト画像を登録しました。'
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
    redirect_to morning_activity_results_path(month: Date.current) if logged_in?
  end

  def terms; end
end

app/controllers/today_morning_activity_results_controller.rb
class TodayMorningActivityResultsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :update, only: %i[new]

  def new; end

  # 本日のデータ取得
  def show
    @day_result = current_user.morning_activity_results.find_by(execution_at: Date.current.all_day)
    respond_to do |format|
      format.json { render json: @day_result }
    end
  end

  def update
    @day_result = current_user.morning_activity_results.find_by(execution_at: Date.current.all_day, state: :not_implemented)
    return unless @day_result

    if @day_result.success!
      flash[:success] = 'データの更新に成功しました。'
    else
      redirect_to root_path, danger: 'データの更新に失敗しました。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/delete_completed.html.erb
<div class='account-delete-completed-wrapper'>
  <div class='container'>
    <div class='delete-completed-message'>
      アカウントは正常に削除されました。<br>
      ご利用頂きありがとうございました。<br>
      再度サービスを開始する場合は、<br>
      Twitterログインをお願いします。<br>
    </div>
  </div>
</div>

app/views/accounts/delete_confirm.html.erb
<div class='account-delete-confirm-wrapper'>
  <div class='container'>
    <h1 class='page-headding'>
      アカウント削除
    </h1>
    <div class='page-body'>
      <div class='delete-confirm-text'>
        削除手続きをされますと、<br>
        アプリをご利用できなくなります。<br>
        削除してよろしいでしょうか？<br>
      </div>
      <div class='delete-confirm-buttons'>
        <%= link_to 'キャンセル', account_path, class: 'btn btn-primary cancel-button' %>
        <%= link_to '削除する', account_path, method: :delete, class: 'btn btn-primary delete-button' %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class='account-wrapper'>
  <div class='container'>
    <h1 class='page-headding'>
      マイページ設定
    </h1>
    <div class='page-body'>
      <div class='mypage-content-frame'>
        <div class='mypage-content-headding'>
          自動ツイート画像設定
        </div>
        <%= render 'shared/picture_settings' %>
      </div>
      <div class='mypage-content-frame'>
        <div class='mypage-content-headding'>
          アカウント削除
        </div>
        <%= link_to 'アカウントを削除', accounts_delete_confirm_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class='account-wrapper'>
  <div class='container'>
    <h1 class='page-headding'>
      マイページ設定
    </h1>
    <div class='page-body'>
      <div class='mypage-content-frame'>
        <div class='mypage-content-headding'>
          自動ツイート画像設定
        </div>
        <%= render 'shared/post_picture' %>
      </div>
      <div class='mypage-content-frame'>
        <div class='mypage-content-headding'>
          アカウント削除
        </div>
        <%= link_to 'アカウントを削除', account_delete_confirm_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/activity_plans/new.html.erb
<div class='activity-plans-wrapper'>
  <div class='container activity-plans-container'>
    <div class='start-message'>
      朝活スタートボタンが押下されました！<br>
      本日の自動ツイートは行われません。<br>
      <br>
      次に朝活の内容を投稿してみましょう！<br>
    </div>
    <div class='post-select-button'>
      <%= link_to '投稿をスキップする', morning_active_path(current_user), class: 'btn btn-primary post-skip-button' %>
      <%= link_to '投稿する', "https://twitter.com/share?text=今から朝活で下記の内容を行います。%0a・%0a&url=https://www.url.url/&hashtags=朝活,アサカツ", onClick: "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;", rel: 'nofollow', class: 'btn btn-primary twitter-link' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MorningActivity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id='wrapper'>
      <% if logged_in? && !current_page?(site_term_path) %>
        <%= render 'shared/header' %>
      <% else %>
        <%= render 'shared/before_login_header' %>
      <% end %>
      <%= render 'shared/flash_message' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/morning_actives/show.html.erb
<div class='morning-active-wrapper'>
  <div class='container'>
    <div class='morning-active-text'>
      朝活予定日の午前中のみボタンをクリックできます。<br>
      正午までにクリックしない場合自動ツイートされます。<br>
      <br>
      日付をクリックすると朝活予定日で登録されます。<br>
      再度クリックすることで解除できます。<br>
      ※過去の日付は解除できません。<br>
    </div>
    <div class='start-button'>
      <%= button_to '朝活スタート', new_activity_plan_path, class: 'button-link btn btn-primary', id: 'js-activity-button', disabled: true, method: :get %>
    </div>
    <div class='calendar-color-message'>
      黄:本日、緑:予定日、青:成功、赤:失敗<br>
    </div>
    <div id='calendar' data-json="<%= current_user.id.to_json %>" ></div>
  </div>
</div>

app/views/morning_activity_results/index.html.erb
<div class='morning-active-wrapper'>
  <div class='container'>
    <div class='morning-active-text'>
      朝活予定日の午前中のみボタンをクリックできます。<br>
      正午までにクリックしない場合自動ツイートされます。<br>
      <br>
      日付をクリックすると朝活予定日で登録されます。<br>
      再度クリックすることで解除できます。<br>
      ※過去の日付は解除できません。<br>
    </div>
    <div class='start-button'>
      <%= button_to '朝活スタート', new_today_morning_activity_result_path, class: 'button-link btn btn-primary', id: 'js-activity-button', disabled: true, method: :get %>
    </div>
    <div class='calendar-color-message'>
      黄:本日、緑:予定日、青:成功、赤:失敗<br>
    </div>
    <div id='calendar' data-json="<%= current_user.id.to_json %>" ></div>
  </div>
</div>

app/views/picture_settings/index.html.erb
<div class='picture-wrapper'>
  <div class='container'>
    <h1 class='page-headding'>
      寝顔画像を登録しましょう！
    </h1>
    <div class='page-body'>
      <div class='picture-message'>
        朝活失敗時、設定した画像が自動ツイートされます。<br>
        サンプル画像のように寝顔を撮ってみましょう！<br>
        また、マイページより画像の変更が可能です。<br>
      </div>
      <div>
        サンプル画像
      </div>
      <ul class='pictures-example'>
        <li class='picture-example'><%= image_tag 'picture.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture2.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture3.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture4.jpg', size: '200x200' %></li>
      </ul>
      <%= render 'shared/picture_settings' %>
    </div>
  </div>
</div>

app/views/post_pictures/show.html.erb
<div class='picture-wrapper'>
  <div class='container'>
    <h1 class='page-headding'>
      寝顔画像を登録しましょう！
    </h1>
    <div class='page-body'>
      <div class='picture-message'>
        朝活失敗時、設定した画像が自動ツイートされます。<br>
        サンプル画像のように寝顔を撮ってみましょう！<br>
        また、マイページより画像の変更が可能です。<br>
      </div>
      <div>
        サンプル画像
      </div>
      <ul class='pictures-example'>
        <li class='picture-example'><%= image_tag 'picture.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture2.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture3.jpg', size: '200x200' %></li>
        <li class='picture-example'><%= image_tag 'picture4.jpg', size: '200x200' %></li>
      </ul>
      <%= render 'shared/post_picture' %>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <h1 class='header-title'><%= link_to 'アサカツ', root_path, class: 'header-title-link' %></h1>
    <ul class='navbar-nav ml-auto main-nav'>
      <li class='header-login'>
        <%= link_to 'Twitterログイン', auth_at_provider_path(provider: :twitter), class: 'header-login-link' %>
      </li>
    </ul>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='copyright text-center'>
          <p>Copyright © 2020. Asakatsu All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <h1 class='header-title'><%= link_to 'アサカツ', root_path, class: 'header-title-link' %></h1>
    <ul class='navbar-nav ml-auto main-nav header-menu'>
      <li class='nav-item header-username'>
        <%= current_user.name %>
      </li>

      <li class='nav-item dropdown dropdown-slide header-profile'>
        <%= link_to '#', class: 'nav-link', id: 'header-profile', data: {toggle: 'dropdown'}, aria: {haspopup: true}, aria: {expanded: false} do %>
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: 'rounded-circle mr15', size: '40' %>
          <% end %>
        <% end %>
        <div class='dropdown-menu dropdown-menu-right'>
          <div class='dropdown-item'><%= current_user.name %></div>
          <%= link_to '朝活', morning_activity_results_path(month: Date.current), class: 'dropdown-item' %>
          <%= link_to '設定', account_path, class: 'dropdown-item' %>
          <%= link_to 'ログアウト', oauth_logout_path, method: :post, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </nav>
</header>

app/views/shared/_picture_settings.html.erb
<%# <%= form_with model: @user, url: picture_settings_create_path(current_user), method: :post, class: 'form-picture', local: true do |form| %>
<%= form_with url: picture_settings_create_path(current_user), method: :post, class: 'form-picture', local: true do |form| %>
  <div class='picture-zone'>
    <div>
      自動ツイート用画像
    </div>
    <%# 画像登録の有無で表示する画像を切り替え%>
    <% if current_user.post_picture.attached? %>
      <%= image_tag current_user.post_picture, size: '400x250', id: 'js-picture-preview', class: 'picture-preview' %>
    <% else %>
      <%= image_tag 'picture.jpg', size: '400x250', id: 'js-picture-preview', class: 'picture-preview' %>
    <% end %>
  </div>
  <div class='picture-setting-buttons'>
    <label>
      <span class="btn btn-primary">
        画像選択
        <%= form.file_field :post_picture, id: 'js-post-picture', class: 'post-picture' %>
      </span>
    </label>
    <%= form.submit '登録', class: 'btn btn-primary', name: 'register', data: {'disable-with': '指定した画像を登録'} %>
    <%= form.submit 'デフォルト画像を登録', class: 'btn btn-primary', name: 'default_register', data: {'disable-with': 'デフォルト画像を登録'}, data: { confirm: 'デフォルト画像が設定されてしまします。よろしいでしょうか？' } %>
  </div>
<% end %>

app/views/shared/_post_picture.html.erb
<%= form_with url: post_picture_path, method: :post, class: 'form-picture', local: true do |form| %>
  <div class='picture-zone'>
    <div>
      自動ツイート用画像
    </div>
    <%# 画像登録の有無で表示する画像を切り替え%>
    <% if current_user.post_picture.attached? %>
      <%= image_tag current_user.post_picture, size: '400x250', id: 'js-picture-preview', class: 'picture-preview' %>
    <% else %>
      <%= image_tag 'picture.jpg', size: '400x250', id: 'js-picture-preview', class: 'picture-preview' %>
    <% end %>
  </div>
  <div class='picture-setting-buttons'>
    <label>
      <span class="btn btn-primary">
        画像選択
        <%= form.file_field :post_picture, id: 'js-post-picture', class: 'post-picture' %>
      </span>
    </label>
    <%= form.submit '登録', class: 'btn btn-primary', data: {'disable-with': '登録'} %>
    <%= link_to 'デフォルト画像を登録', post_picture_path, method: :delete, class: 'btn btn-primary', data: { confirm: 'デフォルト画像が設定されてしまいます。よろしいでしょうか？' } %>
  </div>
<% end %>

app/views/sites/_terms_text.html.erb
<div class='terms-scroll-top' align="center">
  <div class='terms-scroll-middle'>
    <div class='terms-scroll-buttom'>
      <p>この利用規約（以下、「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

      <h1>第1条(適用)</h1>
      <p>本規約は、ユーザーと本サービス運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>

      <h1>第2条(利用登録)</h1>
      <p>1. 登録希望者が本サービスの定める方法によって利用登録を申請し，本サービス運営者がこれを承認することによって，利用登録が完了するものとします。<br>
      2. 本サービスは，TwitterAPIを利用した認証による利用登録を採用しています。本サービスの仕様上，ユーザーのTwitterアカウントが非公開アカウントの場合，本サービスの利用ができない仕様となっておりますので，あらかじめご了承ください。</p>

      <h1>第3条(ユーザー情報の利用目的)</h1>
      <p>本サービスは，ユーザーのTwitterアカウントに関して，以下の情報を取得します。<br>
      (1) TwitterID(ユーザーに一意で付与される数字の羅列のデータ)(例. 99999999999999)<br>
      (2) Twitter上の名前(例. しんさく@社内唯一のエンジニア)<br>
      (3) Twitter上のプロフィールアイコン<br>
      (4) Twitter上のアクセストークン、シークレットトークン<br>
(1)、(2)、(3)は、本サービスにおけるプロフィールとしての目的で利用する情報です。(4)はユーザーが設定した朝活予定日に対して、日本時間で午前0時〜12時の間にスタートボタンを押下しない場合に自動ツイート機能として使用します。</p>

      <h1>第4条(禁止事項)</h1>
      <p>ユーザーは、本サービスの利用にあたり，以下の行為をしてはなりません。<br>
      (1) 法令または公序良俗に反する行為<br>
      (2) 犯罪行為に関連する行為<br>
      (3) 本サービスのサーバーまたはネットワークの機能を破壊したり，妨害したりする行為<br>
      (4) 本サービスの運営を妨害するおそれのある行為<br>
      (5) 他のユーザーに関する個人情報等を収集または蓄積する行為<br>
      (6) 他のユーザーに成りすます行為<br>
      (7) 本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為<br>
      (8) その他，本サービスの運営者が不適切と判断する行為</p>

      <h1>第5条(本サービスの提供の停止等)</h1>
      <p>1. 本サービスの運営者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      (1) 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br>
      (2) 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合<br>
      (3) コンピュータまたは通信回線等が事故により停止した場合<br>
      (4) その他，本サービスの運営者が本サービスの提供が困難と判断した場合<br>
2. 本サービスの運営者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</p>

      <h1>第6条(利用制限および登録抹消)</h1>
      <p>1. 本サービスの運営者は，以下の場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。(1) 本規約のいずれかの条項に違反した場合(2) その他，当社が本サービスの利用を適当でないと判断した場合2. 本サービスの運営者は，本条に基づき本サービスの運営者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>

      <h1>第7条(免責事項)</h1>
      <p>本サービスの運営者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>

      <h1>第8条(サービス内容の変更等)</h1>
      <p>本サービスの運営者は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

      <h1>第9条(利用規約の変更)</h1>
      <p>本サービスの運営者は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</p>
    </div>
  </div>
</div>

app/views/sites/index.html.erb
<div class='site-wrapper'>
  <div class='container'>
    <div class='top-inner-text'>
      <div class='site-introduction'>
        <p>
        朝の時間を有効活用したい人が、<br>
        Twitterと連携して、<br>
        朝活を習慣づけるためのアプリ。<br>
        </p>
      </div>
      <div class='login-button'>
        <%= link_to 'Twitterログイン', auth_at_provider_path(provider: :twitter), class: 'button-link' %>
      </div>
    </div>
  </div>
</div>

app/views/sites/term.html.erb
<div class='top-wrapper'>
  <div class='container'>
    <div class='top-inner-text'>
      <p class='terms-title'>
        利用規約
      </p>
      <%= render 'terms_text' %>
      <p class='terms-message'>
      ※朝活を失敗した場合に自動ツイートがされてしまいます。
      </p>
      <div class='check-confirm'>
        <%= check_box_tag :checkbox %>
        <%= label_tag :checkbox, '利用規約に同意する' %>
      </div>
      <div class='next-button'>
          <%= button_to '次へ', post_picture_path, id: 'next-button', disabled: true, method: :get, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/today_morning_activity_results/new.html.erb
<div class='activity-plans-wrapper'>
  <div class='container activity-plans-container'>
    <div class='start-message'>
      朝活スタートボタンが押下されました！<br>
      本日の自動ツイートは行われません。<br>
      <br>
      次に朝活の内容を投稿してみましょう！<br>
    </div>
    <div class='post-select-button'>
      <%= link_to '投稿をスキップする', morning_activity_results_path(month: Date.current), class: 'btn btn-primary post-skip-button' %>
      <%= link_to '投稿する', "https://twitter.com/share?text=今から朝活で下記の内容を行います。%0a・%0a&url=http://52.195.4.183/&hashtags=朝活,アサカツ", onClick: "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;", rel: 'nofollow', class: 'btn btn-primary twitter-link' %>
      </div>
    </div>
  </div>
</div>